import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainLayout from "@/layout/MainLayout";
import { CartProvider } from "@/context/CartContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
       
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="container-xxl bg-white p-0">
          <CartProvider>
            <MainLayout>{children}</MainLayout>
          </CartProvider>
        </div>
        <script
          src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.0-alpha1/js/bootstrap.bundle.min.js"
          integrity="sha384-pzjw8f+ua7Kw1TIq0lZ9zU1p3MjF7nnt4rpeJr59g5paI+PBJzDqD/ZrxHIZ5ey1"
          crossOrigin="anonymous"
          defer
        ></script>
      </body>
    </html>
  );
}
